BUGFIX: AbstractMethod-, Instantiation-, NoSuchField- and NoSuchMethodErrors no longer force application to quit.
git-svn-id: file:///Users/q/development/git/svnroot/trunk/Wonder@3089 8dc76679-1c23-de11-85cd-0050568e728b