check boolean (5.4.2) variant first, also catch Throwable not Exception, because this throws a NoSuchMethodError
git-svn-id: file:///Users/q/development/git/svnroot/trunk/Wonder@8130 8dc76679-1c23-de11-85cd-0050568e728b