The call to ERXProperties.evaluatePropertyOperators() is causing a NoSuchMethodError for some reason no time to debug right now, will comment out and debug later.
git-svn-id: https://wonder.svn.sourceforge.net/svnroot/wonder/branches/Wonder_2_0_0_Branch@7251 8dc76679-1c23-de11-85cd-0050568e728b